config/routes.rb
Rails.application.routes.draw do
  resources :food_items do
    resources :orders
    resources :reviews
    # food_items/:food_item_id/orders/new
  end
  get 'contact_us' => 'home#contact_us'
  get 'menu' => 'home#menu'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food_item.rb
class FoodItem < ApplicationRecord
  has_many :orders, dependent: :destroy
  has_many :reviews, dependent: :destroy

  validates :name, :section, :price, presence: true
  validates :price, numericality: true

  def image_url
    if remote_image_url.present?
      remote_image_url
    else
      "http://loremflickr.com/320/240/#{CGI.escape name}"
    end
  end

  def average_review_score
    scores = self.reviews.pluck(:score)
    average_score = scores.inject{ |sum, el| sum + el }.to_f / scores.size
    return average_score.round(2)
  end

end

app/models/food_type.rb
class FoodType
	def self.all
		%w(Asian Western)
	end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :food_item
  validates :food_item, :name, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :food_item
end

app/models/section.rb
class Section
	def self.all
		%w(Breakfast Lunch Dinner Drinks)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/food_items_controller.rb
class FoodItemsController < ApplicationController
  before_action :set_food_item, only: [:show, :edit, :update, :destroy]

  # GET /food_items
  # GET /food_items.json
  def index
    @food_items = FoodItem.all
  end

  # GET /food_items/1
  # GET /food_items/1.json
  def show
    @food_item = FoodItem.find params[:id]
    if @food_item.food_view == nil
      @food_item.food_view = 1
    else
      @food_item.food_view += 1
    end
    @food_item.save
  end

  # GET /food_items/new
  def new
    @food_item = FoodItem.new
  end

  # GET /food_items/1/edit
  def edit
  end

  # POST /food_items
  # POST /food_items.json
  def create
    @food_item = FoodItem.new(food_item_params)
    @food_item.food_view = 0

    respond_to do |format|
      if @food_item.save
        format.html { redirect_to @food_item, notice: 'Food item was successfully created.' }
        format.json { render :show, status: :created, location: @food_item }
      else
        format.html { render :new }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /food_items/1
  # PATCH/PUT /food_items/1.json
  def update
    respond_to do |format|
      if @food_item.update(food_item_params)
        format.html { redirect_to @food_item, notice: 'Food item was successfully updated.' }
        format.json { render :show, status: :ok, location: @food_item }
      else
        format.html { render :edit }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /food_items/1
  # DELETE /food_items/1.json
  def destroy
    @food_item.destroy
    respond_to do |format|
      format.html { redirect_to food_items_url, notice: 'Food item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food_item
      @food_item = FoodItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_item_params
      params.require(:food_item).permit(:name, :description, :price, :section, :food_type, :remote_image_url)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
  end

  def contact_us
	end

	def menu
		if params[:search]
			@food_items = FoodItem.where("lower(name) LIKE ?", "%#{params[:search]}%".downcase)
		else
			@food_items = FoodItem.all
		end

		if params[:section] && params[:section] != ""
			@food_items = @food_items.where section: params[:section]
		end

		if params[:food_type] && params[:food_type] != ""
			@food_items = @food_items.where food_type: params[:food_type]
		end

		if params[:sort_column]
			@food_items = @food_items.order("#{params[:sort_column]} #{params[:sort_direction]}")
		end 
	end
	
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    @food_item = FoodItem.find params[:food_item_id ]
  end

  def create
    @food_item = FoodItem.find params[:food_item_id ]

    @order = Order.new(order_params)
    @order.food_item = @food_item

    if @order.save
      # Tell the UserMailer to send a welcome email after save
      OrderMailer.place_order_email(@order).deliver_later
      flash[:success] = "Order submitted. Thank you!"
      redirect_to food_item_order_path(id: @order.id)
    else
      flash[:error] = "Error: #{@order.errors.full_messages.to_sentence}"
      render 'new'
    end
  end

  def show
    @order = Order.find params[:id]
    @food_item = FoodItem.find @order.food_item_id
  end

  private
  def order_params
    params.require(:order).permit(:name, :phone, :address, :discount_code)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @food_item = FoodItem.find(params[:food_item_id])
    @review = @food_item.reviews.create(review_params)
    flash[:notice] = "Feeback sent"
    redirect_to food_item_path(@food_item)
  end

  private

  def review_params
    params.require(:review).permit(:score, :reviewer, :feedback)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/food_items_helper.rb
module FoodItemsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/food_items/_form.html.erb
<%= form_for(food_item) do |f| %>
  <% if food_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(food_item.errors.count, "error") %> prohibited this food_item from being saved:</h2>

      <ul>
      <% food_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: 'form-control-label' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :description, class: 'form-control-label' %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :price, class: 'form-control-label' %>
    <%= f.text_field :price, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :section, class: 'form-control-label' %>
    <%= f.text_field :section, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :food_type, class: 'form-control-label' %>
    <%= f.text_field :food_type, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :remote_image_url, class: 'form-control-label' %>
    <%= f.text_field :remote_image_url, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/food_items/edit.html.erb
<h1>Editing Food Item</h1>

<%= render 'form', food_item: @food_item %>

<%= link_to 'Show', @food_item %> |
<%= link_to 'Back', food_items_path %>

app/views/food_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Food Items</h1>

<table class="table table-striped ">
  <thead class="thead thead-default ">
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Section</th>
      <th>Remote image url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @food_items.each do |food_item| %>
      <tr>
        <td><%= food_item.name %></td>
        <td><%= food_item.description %></td>
        <td><%= food_item.price %></td>
        <td><%= food_item.section %></td>
        <td><%= food_item.food_type %></td>
        <td><%= image_tag food_item.image_url %></td>
        <td><%= link_to 'Show', food_item %></td>
        <td><%= link_to 'Edit', edit_food_item_path(food_item) %></td>
        <td><%= link_to 'Destroy', food_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Food Item', new_food_item_path, class: 'btn btn-secondary' %>

app/views/food_items/new.html.erb
<h1>New Food Item</h1>

<%= render 'form', food_item: @food_item %>

<%= link_to 'Back', food_items_path %>

app/views/food_items/show.html.erb
<div class="card">
  <div class="card-block">
    <h1 class="card-title">
      <%= @food_item.name %>
      <% if @food_item.orders.size > 0 %>
        <span class="tag tag-default"><%= @food_item.orders.size %></span>
      <% end %>
    </h1>
    <h1>
      <span class="tag tag-success"><%= @food_item.price %></span>
    </h1>
    <h3>
      <span class="tag tag-info"><%= @food_item.section %></span>
      <span class="tag tag-info"><%= @food_item.food_type %></span>
    </h3>
    <% if @food_item.food_view != nil %>
      <b>Viewed:</b> <%= @food_item.food_view %>
    <% end %>
    <p class="card-text"><%= @food_item.description %></p>
  </div>
  <div class="card-block">
    <%= image_tag @food_item.image_url, width: '640', class: 'card-img-top' %>
  </div>
  <% if @food_item.reviews.count > 0 %>
    <div class="card-block">
      <h3>All feedback - <%= @food_item.average_review_score %> / 5</h3>
      <%= render @food_item.reviews.order("created_at DESC") %>
    </div>
  <% end %>
  <div class="card-block">
    <h3>Leave feedback</h3>
    <%= form_for [@food_item, @food_item.reviews.build] do |f| %>
      <div class="form-group">
        <%= f.label :score %>
        <%= f.number_field :score, in: 1..5, step: 1, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :reviewer %>
        <%= f.text_field :reviewer, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :feedback %>
        <%= f.text_area :feedback, class: "form-control"  %>
      </div>
      <div class="actions">
        <%= f.submit "Send", class: "btn btn-default" %>
      </div>
    <% end %>
  </div>
  <div class="card-footer">
    <%= link_to 'Back', menu_path, class: 'card-link btn btn-secondary' %>
  </div>
</div>

app/views/home/contact_us.html.erb
<h1>WE ARE SOMEWHERE IN SAIGON</h1>

<div class="row">
	<div class="col-xs-3">
		<h3>Address</h3>
		<address>
			5/4 Lê Quý Đôn<br>
			phường 14<br>
			Quận 3<br>
			Hồ Chí Minh<br>
			Việt Nam<br>
		</address>
		<h3>Phone</h3>
		0908070605
	</div>
 	<div class="col-xs-9">
 		<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3919.2611837810255!2d106.67835531538819!3d10.79129699231151!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x317528d4c0d9cff1%3A0x1debe3e4bc5536ab!2zNS80IEzDqiBRdcO9IMSQw7RuLCBwaMaw4budbmcgMTQsIFF14bqtbiAzLCBI4buTIENow60gTWluaCwgVmnhu4d0IE5hbQ!5e0!3m2!1svi!2s!4v1476519829241" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
	</div>
</div>

app/views/home/index.html.erb
<div class="jumbotron">
  <h1 class="display-3">NHÀ HÀNG TỐIIII!</h1>
  <p class="lead">Vâng, nhà hàng chúng tôi rất tối, rất rất tối</p>
  <hr class="m-y-2">
  <p>Do you have money?</p>
  <p class="lead"> 
    <%= link_to "Menu", menu_path, class: 'btn btn-secondary btn-lg' %>
    <%= link_to "Contact Us", contact_us_path, class: 'btn btn-secondary btn-lg' %>
  </p>
</div>

app/views/home/menu.html.erb
<h1>Menu</h1>

<div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
	<div class="btn-group" role="group" aria-label="Section group">
		<% Section.all.each do |section| %>
		 <%= link_to section, menu_path(section: section, search: params[:search]), class: "btn btn-secondary #{'active' if params[:section] == section}" %>
		<% end %>
	</div>
	<div class="btn-group" role="group" aria-label="FoodType group">
		<% FoodType.all.each do |food_type| %>
			<%= link_to food_type, menu_path(food_type: food_type, search: params[:search]), class: "btn btn-secondary #{'active' if params[:food_type] == food_type}" %>
		<% end %>
	</div>
</div>

<div class="card card-block">
	<%= form_tag nil, method: 'get' do %>
	<%= hidden_field_tag :section, params[:section] %>
	<%= hidden_field_tag :food_type, params[:food_type] %>
	<%= hidden_field_tag :search, params[:search] %>
		<div class="form-inline">
			<%= select_tag :sort_column, options_for_select([['Name', 'name'], ['Price', 'price'], ["Viewed", 'food_view']]), class: 'form-control' %>
			<%= select_tag :sort_direction, options_for_select([['Ascending', 'asc'], ['Descending', 'desc']]), class: 'form-control' %>
			<%= submit_tag "Sort", class: 'btn btn-secondary' %> 
		</div>  
	<% end %>
</div>

<% @food_items.in_groups_of(3) do |group| %>
	<div class="row">
		<% group.compact.each do |food_item| %>
			<div class="col-sm-4">
				<div class="card">
					<%= image_tag food_item.image_url, class: 'card-img-top' %>
					<div class="card-block">
						<h4 class="card-title">
							<%= link_to food_item.name, food_item_path(food_item.id) %>
							<% if food_item.orders.size > 0 %>
								<span class="tag tag-default"><%= food_item.orders.size %></span>
							<% end %>
						</h4>
						<h3>
							<span class="tag tag-success"><%= food_item.price %></span>
						</h3>
						<% if food_item.food_view != nil %>
							<b>Viewed:</b> <%= food_item.food_view %>
						<% end %>
						<p class="card-text"><%= food_item.description %></p>
					</div>
					<div class="card-block">
						<%= link_to "Order", new_food_item_order_path(food_item_id: food_item.id), class: 'card-link btn btn-danger' %>
						<!-- <a href="#" class="card-link btn btn-danger">Order</a> -->
					</div>
				</div>
			</div>
		<% end %>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Restaurant</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<nav class="navbar navbar-light bg-faded">
	  <a class="navbar-brand" href="<%= root_path %>">Home</a>
	  <ul class="nav navbar-nav">
	    <li class="nav-item <%= 'active' if current_page?(menu_path) %>">
	    	<%= link_to "Menu", menu_path, class: 'nav-link' %>
	    </li>
	    <li class="nav-item <%= 'active' if current_page?(contact_us_path) %>">
	    	<%= link_to "Contact us", contact_us_path, class: 'nav-link' %>
	    </li>
	  </ul>
	  <%= form_tag menu_path, class: 'form-inline pull-xs-right', :method => 'get' do %>
	    <%= text_field_tag :search, params[:search], placeholder: 'Search', class: 'form-control' %>
	    <%= submit_tag "Search", :name => nil, class: 'btn btn-outline-success' %>
    <% end %>
	</nav>

	<div class="container">
		<% if flash[:error] %>
			<div class="alert alert-danger"><%= flash[:error] %></div>
		<% end %>
		<% if flash[:success] %>
			<div class="alert alert-success"><%= flash[:success] %></div>
		<% end %>
		<%= yield %>
	</div>
  </body>
</html>
 

app/views/orders/new.html.erb
<h1>
	<small>Order for</small> <%= @food_item.name %>
</h1>

<%= form_for [@food_item, Order.new] do |f| %>
	<div class="form-group">
		<%= f.label :name, class: 'form-control-label' %>
		<%= f.text_field :name, class: 'form-control' %>
	</div>
	<div class="form-group">
		<%= f.label :phone, class: 'form-control-label' %>
		<%= f.text_field :phone, class: 'form-control' %>
	</div>
	<div class="form-group">
		<%= f.label :address, class: 'form-control-label' %>
		<%= f.text_area :address, class: 'form-control' %>
	</div>
	<div class="form-group">
		<%= f.label :discount_code, class: 'form-control-label' %>
		<%= f.text_field :discount_code, class: 'form-control' %>
	</div>
	<div class="actions">
		<%= f.submit "Submit Order", class: 'btn btn-primary' %>
	</div>
<% end %>

app/views/orders/show.html.erb
<div class="card">
  <div class="card-block">
    <h1 class="card-title">
      Thank you <%= @order.name %> for placing order with us!
    </h1>
    <p>YOUR ORDER</p>
    <b>Order Number:</b> <%= @order.id %><br>
    <b>Order Item:</b> <%= @food_item.name %><br>
    <b>Placed order at:</b> <%= @order.created_at.to_time.strftime('%a %b %d %H:%M:%S') %><br>
    <b>Quantaty:</b> 1<br>
    <b>Delivery fee:</b> 20000
    <hr>
    <p>DELIVERY INFO</p>
    <b>Contact:</b> <%= @order.name %><br>
    <b>Phone:</b> <%= @order.phone %><br>
    <b>Address:</b> <%= @order.address %>
    <hr>
    <p>TOTAL</p>
    <% if @order.discount_code == "CODERSCHOOL" %>
      <%= (@food_item.price + 20000)/2 %>
    <% else %>
      <%= @food_item.price + 20000 %>
    <% end %>
  </div>
  <div class="card-footer">
    <%= link_to 'Back', menu_path, class: 'card-link btn btn-secondary' %>
  </div>
</div>

app/views/reviews/_review.html.erb
<div>
  <div>
    <b>Score</b>: <%= review.score %>
  </div>
  <div>
    <%= review.reviewer %>: <%= review.feedback %>
  </div>
</div>